Repository replayio/devtools, pull requests merged in 2022-04, with the labels that each got.

#6075 Update react-devtools-inline, react, and react-dom dependencies
  package-lock.json
  package.json
  src/ui/components/SecondaryToolbox/ReactDevTools.tsx
  src/ui/components/SecondaryToolbox/react-devtools-inline.d.ts
Labels: Bug

#6359 Initialize the messages state earlier
  src/ui/setup/dynamic/devtools.ts
  src/ui/setup/index.ts
  src/ui/setup/store.ts
Labels: has-replay 💪

#6284 Apply the accordion package to the Pause Info panel
  packages/accordion/index.tsx
  src/devtools/client/debugger/src/components/SecondaryPanes/Breakpoints/index.js
  src/devtools/client/debugger/src/components/SecondaryPanes/BreakpointsPane.tsx
  src/devtools/client/debugger/src/components/SecondaryPanes/LogpointsPane.tsx
  src/devtools/client/debugger/src/components/SecondaryPanes/index.js
  src/devtools/client/debugger/src/components/SecondaryPanes/index.tsx
  src/devtools/client/debugger/src/utils/prefs.js
  src/ui/components/SecondaryToolbox/index.tsx
Labels: has-replay 🚀

#6367 Don't navigate the timeline while the user is dragging the zoom handlebars
  src/ui/components/Timeline/index.tsx
Labels: has-replay 🚀

#6333 Add an unread badge for the comment icon in the sidebar
  src/ui/components/Toolbar.tsx
  src/ui/components/Toolbox.css
Labels: has-replay 🚀

#6399 Fix comment badge behavior
  src/ui/components/Toolbar.tsx
Labels: has-replay 🚀

#6411 Fix removing breakpoints/logpoints from the sidepanel
  src/devtools/client/debugger/src/components/SecondaryPanes/Breakpoints/index.js
  src/devtools/client/debugger/src/components/SecondaryPanes/BreakpointsPane.tsx
  src/devtools/client/debugger/src/components/SecondaryPanes/LogpointsPane.tsx
Labels: has-replay 🚀

#6441 Update heatmap hits count when the backend unloads a region forcibly
  src/devtools/client/debugger/src/reducers/source-actors.ts
Labels: has-replay 🚀

#6408 Add CMD+F (search) to Console
  package-lock.json
  package.json
  src/devtools/client/debugger/src/components/shared/SearchInput.js
  src/devtools/client/shared/react.d.ts
  src/devtools/client/themes/webconsole.css
  src/devtools/client/webconsole/components/App.tsx
  src/devtools/client/webconsole/components/Input/JSTerm.tsx
  src/devtools/client/webconsole/components/Output/ConsoleOutput.tsx
  src/devtools/client/webconsole/components/Output/Message.js
  src/devtools/client/webconsole/components/Output/MessageContainer.js
  src/devtools/client/webconsole/components/Output/MessageContainer.module.css
  src/devtools/client/webconsole/components/Output/message-types/ConsoleApiCall.js
  src/devtools/client/webconsole/components/Output/message-types/ConsoleCommand.js
  src/devtools/client/webconsole/components/Output/message-types/EvaluationResult.js
  src/devtools/client/webconsole/components/Output/message-types/PageError.js
  src/devtools/client/webconsole/components/Output/message-types/PaywallMessage.js
  src/devtools/client/webconsole/components/Search/ConsoleSearch.module.css
  src/devtools/client/webconsole/components/Search/ConsoleSearch.tsx
  src/devtools/client/webconsole/components/Search/ConsoleSearchContext.tsx
  src/devtools/client/webconsole/components/Search/index.ts
  src/devtools/client/webconsole/components/Search/useConsoleSearch.test.tsx
  src/devtools/client/webconsole/components/Search/useConsoleSearch.ts
  src/devtools/client/webconsole/components/Search/useSearch.test.tsx
  src/devtools/client/webconsole/components/Search/useSearch.ts
  src/devtools/client/webconsole/selectors/messages.ts
  src/ui/reducers/app.ts
  src/ui/utils/timeline.ts
Labels: feature-console

#6452 NPM lint rule uses Trunk to better align with CI
  package.json
Labels: Tooling

#6453 Update Trunk and ESLint dependencies
  .github/workflows/lint.yml
  .trunk/trunk.yaml
  package-lock.json
  package.json
Labels: Dependencies, Tooling

#6478 Show images in the Network Monitor
  src/ui/components/NetworkMonitor/BodyDownload.tsx
  src/ui/components/NetworkMonitor/HttpBody.tsx
  src/ui/components/NetworkMonitor/content.test.tsx
  src/ui/components/NetworkMonitor/content.ts
Labels: feature-net-monitor

#6530 Don't set pointer-events none to the gutter's + button
  src/devtools/client/debugger/src/components/Editor/Breakpoints/Breakpoints.css
  src/devtools/client/debugger/src/components/Editor/ToggleWidgetButton.tsx
Labels: has-replay 🚀
